#ifndef __ENUM_ASSET__
#define __ENUM_ASSET__

typedef enum ASSET
{
    ASSET_MIN = 0x0000,


    ASSET_INTROTEXT_SHAMANS = 0x018AC,
    ASSET_INTROTEXT_SM_1,
    ASSET_INTROTEXT_SM_2,
    ASSET_INTROTEXT_MT,
    ASSET_INTROTEXT_GGM,
    ASSET_INTROTEXT_WW,
    ASSET_INTROTEXT_JRL,
    ASSET_INTROTEXT_TDL,
    ASSET_INTROTEXT_GI,
    ASSET_INTROTEXT_HFP,
    ASSET_INTROTEXT_CCL,
    ASSET_INTROTEXT_CK,
    ASSET_INTROTEXT_IOH,
    ASSET_INTROTEXT_UNK, //!
    ASSET_INTROTEXT_MULTIPLAYER


} ASSET;



#endif // __ENUM_ASSET__
