#ifndef __ENUM_ASSET__
#define __ENUM_ASSET__

typedef enum ASSET
{
    ASSET_0000_MIN = 0x0000,


    ASSET_18AC_INTROTEXT_SHAMANS = 0x18AC,
    ASSET_18AD_INTROTEXT_SM_1,
    ASSET_18AE_INTROTEXT_SM_2,
    ASSET_18AF_INTROTEXT_MT,
    ASSET_18B0_INTROTEXT_GGM,
    ASSET_18B1_INTROTEXT_WW,
    ASSET_18B2_INTROTEXT_JRL,
    ASSET_18B3_INTROTEXT_TDL,
    ASSET_18B4_INTROTEXT_GI,
    ASSET_18B5_INTROTEXT_HFP,
    ASSET_18B6_INTROTEXT_CCL,
    ASSET_18B7_INTROTEXT_CK,
    ASSET_18B8_INTROTEXT_IOH,
    ASSET_18B9_INTROTEXT_UNK, //!
    ASSET_18BA_INTROTEXT_MULTIPLAYER,


    ASSET_xxxx_MAX
} ASSET;



#endif // __ENUM_ASSET__
