#ifndef __ENUM_ITEM__
#define __ENUM_ITEM__




typedef enum JINJO_COLOUR
{
    JINJO_COLOUR_WHITE,
    JINJO_COLOUR_ORANGE,
    JINJO_COLOUR_YELLOW,
    JINJO_COLOUR_BROWN,
    JINJO_COLOUR_GREEN,
    JINJO_COLOUR_RED,
    JINJO_COLOUR_BLUE,
    JINJO_COLOUR_PINK,
    JINJO_COLOUR_BLACK,

    TOTAL_JINJO_COLOURS,
} JINJO_COLOUR;


typedef enum SPECIAL_ITEM
{
    SPECIAL_ITEMS_JINJOS,
    SPECIAL_ITEMS_JIGGIES,
    SPECIAL_ITEMS_EMPTY_HONEYCOMBS,
    SPECIAL_ITEMS_GLOWBOS,
    SPECIAL_ITEMS_CHEATO_PAGES,
    SPECIAL_ITEMS_TARGITZAN_STATUES,
    SPECIAL_ITEMS_NOTES,
    SPECIAL_ITEMS_DOUBLOONS,
    SPECIAL_ITEMS_WITCHYWORLD_TICKETS,
    SPECIAL_ITEMS_SPAWNED_JINJOS,
    SPECIAL_ITEMS_SPAWNED_JIGGIES,
    SPECIAL_ITEMS_SPAWNED_EMPTY_HONEYCOMBS,
    SPECIAL_ITEMS_SPAWNED_GLOWBOS_,
    SPECIAL_ITEMS_SPAWNED_CHEATO_PAGES,
    SPECIAL_ITEMS_SPAWNED_TARGITZAN_STATUES,
    SPECIAL_ITEMS_SPAWNED_NOTES,
    SPECIAL_ITEMS_SPAWNED_DOUBLOONS,
    SPECIAL_ITEMS_SPAWNED_WITCHYWORLD_TICKETS,
} SPECIAL_ITEM;





#endif // __ENUM_ITEM__

