#ifndef __ENUM_MINIGAME__
#define __ENUM_MINIGAME__

typedef enum MINIGAME
{
    MINIGAME_BALLOON_BURST = 0x80,
    MINIGAME_HOOP_SWOOP,
    MINIGAME_UNKOWN_MINIGAME_0x82,
    MINIGAME_TWINKLIES_PACKING,
    MINIGAME_POT_O_GOLD_1,
    MINIGAME_CHOMPAS_BELLY,
    MINIGAME_TRASH_CAN_GERMS,
    MINIGAME_ZUBBAS_HIVE,
    MINIGAME_MINI_SUB_CHALLENGE,
    MINIGAME_POT_O_GOLD_2,
    MINIGAME_DODGEMS_1,
    MINIGAME_DODGEMS_2,
    MINIGAME_DODGEMS_3,
    MINIGAME_SAUCER_OF_PERIL,
    MINIGAME_MAYAN_KICKBALL_1,
    MINIGAME_MAYAN_KICKBALL_2,
    MINIGAME_MAYAN_KICKBALL_3,
    MINIGAME_COLOSSEUM_KICKBALL_1,
    MINIGAME_COLOSSEUM_KICKBALL_2,
    MINIGAME_COLOSSEUM_KICKBALL_3,
    MINIGAME_CLINKERS_CAVERN,
    MINIGAME_ORDNANCE_STORAGE,
    MINIGAME_JIGGYWIGGY_FINAL_PUZZLE,
} MINIGAME;


#endif // __ENUM_MINIGAME__
