#!/bin/sh

#- Run a hex diff session for a DLL in the terminal with target on top, and ours below
## $1: region
## $2: dll name

(
    hexdiff expected/$1/dlls/$2.bin build/$1/dlls/$2.bin 2>/dev/null
)
